class ChatBot:
    def __init__(self, name):
        self.name = name
        self.responses = {
            "hello": "Hi there!",
            "hi": "Hello!",
            "how are you": "I'm good, thanks! wby?",
            "good": "That's great to hear!",
            "bad": "I'm sorry to hear that. Hope you feel better soon!",
            "what's your name": "My name is {}.".format(name),
            "what's up": "Not much, just chatting!",
            "bye": "See you later!",
            "goodbye": "Goodbye Sir!",
            "help": "I can help you with that!",
            "what can you do": "I can help you with a variety of things. Try asking me something!",
            "thanks": "You're welcome!",
            "default": "I didn't understand that.",
            "how old are you": "I'm ageless!",
            "where are you from": "I'm from the internet!",
            "what do you do": "I'm a chatbot, I chat with users like you!",
            "can you tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
            "can you tell me a story": "Once upon a time, there was a chatbot named {}.".format(name),
            "can you help me with something": "What do you need help with?",
            "can you give me advice": "What's on your mind?",
            "can you recommend something": "What are you looking for?",
            "can you summarize something": "What do you want me to summarize?",
            "can you translate something": "What language do you want me to translate to?",
            "can you define something": "What word do you want me to define?",
            "can you give me an example": "What are you looking for an example of?",
            "can you explain something": "What do you want me to explain?",
            "can you provide more information": "What do you want to know more about?",
            "can you give me a quote": "Here's a quote: 'The only way to do great work is to love what you do.' - Steve Jobs",
            "can you give me a fact": "Here's a fact: The shortest war in history was between Britain and Zanzibar on August 27, 1896, and lasted only 38 minutes.",
            "can you give me a tip": "Here's a tip: Always be kind to others, you never know what they might be going through.",
            "can you give me a warning": "Here's a warning: Be careful what you wish for, you might just get it.",
            "can you give me a suggestion": "Here's a suggestion: Try something new today, you never know what you might discover.",
            "can you give me a recommendation": "Here's a recommendation: Check out this book/movie/TV show, it's really good!",
            "can you give me a review": "Here's a review: I loved it! It was so good!",
            "can you give me a rating": "Here's a rating: 5/5 stars!",
            "can you give me a score": "Here's a score: 100/100!",
            "can you give me a grade": "Here's a grade: A+!",
            "can you give me a percentage": "Here's a percentage: 100%!",
            "can you give me a number": "Here's a number: 42!",
            "can you give me a date": "Here's a date: Today!",
            "can you give me a time": "Here's a time: Now!",
            "can you give me a location": "Here's a location: Everywhere!",
            "can you give me a direction": "Here's a direction: Up!",
            "can you give me a distance": "Here's a distance: Far!",
            "can you give me a speed": "Here's a speed: Fast!",
            "can you give me a temperature": "Here's a temperature: Hot!",
            "can you give me a weather": "Here's a weather: Sunny!",
            "can you give me a forecast": "Here's a forecast: It's going to be a great day!",
            "can you give me a news": "Here's a news: Check out this article!",
            "can you give me a update": "Here's an update: Everything is going well!",
            "can you give me a status": "Here's a status: I'm online!",
            "can you give me a report": "Here's a report: Everything is working as expected!",
            "can you give me a summary": "Here's a summary: It's all good!",
            "can you give me a conclusion": "Here's a conclusion: That's all for now!",
            "can you create a poem": "Here's a poem: 'The sun sets slow and paints the sky, a fiery hue that makes me sigh.'",
            "can you create a song": "Here's a song: 'Imagine all the people living life in peace, you may say I'm a dreamer, but I'm not the only one.'",
            "can you create a story": "Here's a story: 'Once upon a time, in a land far, far away, there was a magical kingdom hidden behind a veil of mist.'",
            "can you create a character": "Here's a character: 'Name: Luna, Age: 25, Occupation: Wizard, Personality: Curious and adventurous.'",
            "can you create a world": "Here's a world: 'Name: Elyria, Location: A mystical realm of wonder and magic, Climate: Temperate with occasional storms.'",
            "can you create a language": "Here's a language: 'Name: Elyrian, Alphabet: 30 characters, Grammar: Subject-verb-object word order.'",
            "can you create a culture": "Here's a culture: 'Name: Elyrian, Values: Respect, kindness, and wisdom, Traditions: Celebrating the summer solstice with feasts and festivals.'",
            "can you create a history": "Here's a history: 'The Elyrian kingdom was founded 1000 years ago by a wise and just king, who united the warring clans and brought peace to the land.'",
            "can you create a mythology": "Here's a mythology: 'The Elyrian pantheon consists of 12 gods and goddesses, each with their own powers and domains.'",
            "can you create a legend": "Here's a legend: 'The legendary sword of Elyria, forged from the metals of the earth and imbued with the magic of the gods.'",
            "can you create a prophecy": "Here's a prophecy: 'A great and powerful leader will arise from the ashes of the old world, and bring peace and prosperity to the land.'",
            "can you create a riddle": "Here's a riddle: 'What can be broken, but never held? What can be given, but never sold?'",
            "can you create a joke": "Here's a joke: 'Why did the scarecrow win an award? Because he was outstanding in his field!'",
            "can you create a pun": "Here's a pun: 'Why did the bicycle fall over? Because it was two-tired!'",
            "can you create a play on words": "Here's a play on words: 'Why did the baker go to the bank? He needed dough!'",
            "can you create a tongue twister": "Here's a tongue twister: 'Percy the python perpetually puckered up a plethora of pickled plums.'",
            "can you create a palindrome": "Here's a palindrome: 'A man, a plan, a canal, Panama!'",
            "can you create a anagram": "Here's an anagram: 'Listen' can be anagrammed into 'Silent'.",
            "can you create a crossword puzzle": "Here's a crossword puzzle: 'ACROSS: 1. Fruit (5), 2. Animal (4), 3. Color (3). DOWN: 1. Sport (6), 2. Music (5), 3. Food (4).'",
            "can you create a word search": "Here's a word search: 'S E A R C H F O R T H E H I D D E N W O R D S.'",
            "can you create a maze": "Here's a maze: 'Start at the top left corner and navigate to the bottom right corner.'",
            "can you create a puzzle": "Here's a puzzle: 'Solve for x: 2x + 5 = 11.'",
            "can you create a game": "Here's a game: 'Guess the number I'm thinking of between 1 and 10.'",
            "can you create a quiz": "Here's a quiz: 'Question: What is the capital of France? A. London, B. Paris, C. Rome.'",
            "can you create a test": "What is the capital of Italy? A. London, B. Paris, C. Rome.'",
            "can you create a brain teaser": "Here's a brain teaser: 'You are in a room with three light switches. Each switch corresponds to one of three light bulbs in a room. Each light bulb is either on or off. You can turn the lights on and off as many times as you want, but you can only enter the room one time to observe the light bulbs. How can you figure out which switch corresponds to which light bulb?'",
            "can you create a logic puzzle": "Here's a logic puzzle: 'There are three switches, but they are not labelled. Each switch corresponds to one of three light bulbs in a room. Each light bulb is either on or off. You can turn the lights on and off as many times as you want, but you can only enter the room one time to observe the light bulbs. How can you figure out which switch corresponds to which light bulb?'",
            "can you create a math problem": "Here's a math problem: 'Solve for x: 2x + 5 = 11.'",
            "can you create a science question": "Here's a science question: 'What is the largest planet in our solar system?'",
            "can you create a history question": "Here's a history question: 'Who was the first president of the United States?'",
            "can you create a geography question": "Here's a geography question: 'What is the capital of France?'",
            "can you create a literature question": "Here's a literature question: 'Who wrote the book 'To Kill a Mockingbird'?'",
            "can you create a music question": "Here's a music question: 'Who was the lead singer of the rock band Queen?'",
            "can you create a movie question": "Here's a movie question: 'What was the name of the movie starring Tom Hanks as a character who was stranded on a deserted island?'",
            "can you create a sports question": "Here's a sports question: 'Which team won the Super Bowl in 2020?'",
            "can you create a game": "Here's a game: 'Guess the number I'm thinking of between 1 and 100.'",
            "can you create a quiz": "Here's a quiz: 'What is the largest planet in our solar system?'",
            "can you create a test": "Here's a test: 'What is the capital of France?'",
            "can you create a survey": "Here's a survey: 'What is your favorite color?'",
            "can you create a poll": "Here's a poll: 'Who do you think will win the next presidential election?'",
            "can you create a debate": "Here's a debate: 'Should the minimum wage be increased?'",
            "can you create a discussion": "Here's a discussion: 'What are the pros and cons of social media?'",
            "can you create a role-playing scenario": "Here's a role-playing scenario: 'You are a detective trying to solve a murder mystery. What do you do first?'",
            "can you create a choose your own adventure story": "Here's a choose your own adventure story: 'You are a brave knight on a quest to slay a dragon. Do you want to go left, right, or straight?'",
            "can you create a interactive story": "Here's an interactive story: 'You are a character in a story and you have to make choices to progress. What do you do?'",
            "can you create a chat game": "Here's a chat game: 'Guess the word I'm thinking of by asking yes or no questions.'",
            "can you create a word game": "Here's a word game: 'Find the word that is hidden in the sentence.'",
            "can you create a trivia game": "Here's a trivia game: 'Answer the questions to win.'",
            "can you create a quiz game": "Here's a quiz game: 'Answer the questions to win.'",
            "can you create a test game": "Here's a test game: 'Answer the questions to win.'",
            "can you create a survey game": "Here's a survey game: 'Answer the questions to win.'",
            "can you create a poll game": "Here's a poll game: 'Answer the questions to win.'",
            "can you create a debate game": "Here's a debate game: 'Argue for or against the topic.'",
            "can you create a discussion game": "Here's a discussion game: 'Discuss the topic and come to a conclusion.'",
            "can you create a role-playing game": "Here's a role-playing game: 'Play the role of a character and make choices to progress.'",
            "can you create a choose your own adventure game": "Here's a choose your own adventure game: 'Make choices to progress through the story.'",
            "can you create a interactive game": "Here's an interactive game: 'Make choices to progress through the story.'",
            "can you create a chat game": "Here's a chat game: 'Guess the word I'm thinking of by asking yes or no questions.'",
            "can you create a word game": "Here's a word game: 'Find the word that is hidden in the sentence.'",
            "can you create a trivia game": "Here's a trivia game: 'Answer the questions to win.'",
            "can you create a quiz game": "Here's a quiz game: 'Answer the questions to win.'",
            "can you create a test game": "Here's a test game: 'Answer the questions to win.'",
            "can you create a survey game": "Here's a survey game: 'Answer the questions to win.'",
            "can you create a poll game": "Here's a poll game: 'Answer the questions to win.'",
            "goodbye": "Goodbye! It was great chatting with you.",
            "see you later": "See you later! Have a great day!",
            "how are you": "I'm good, thanks! How about you?",
            "what's up": "Not much, just hanging out! How about you?",
            "is anyone available": "Let me check if anyone is available. (pause) Yes, someone is available. I'll transfer you to them now.",
            "can i speak with someone": "Let me check if someone is available. (pause) Yes, someone is available. I'll transfer you to them now.",
            "is someone in": "Let me check if someone is in. (pause) Yes, someone is in. I'll transfer you to them now.",
            "can i leave a message": "Yes, you can leave a message. What would you like to say?",
        }


    def respond(self, message):
        message = message.lower()
        for key in self.responses:
            if key in message:
                return self.responses[key]
        return self.responses["default"]
